server:
  port:8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/QLCB
    password: 1122288
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: APIGETWAY-CENTER-SERVER